const MUSIC_LIBRARY = [
  {
    id: '2023-before',
    title: '2023 & Before',
    folder: '2023 & Before',
    cover: 'music/2023.webp',
    coverFallback: 'music/2023 & Before/Folder.jpg',
    durationText: '',
    tracks: [
      { title: 'backofdacoupe', src: 'music/2023 & Before/backofdacoupe.mp3' },
      { title: 'backwoods', src: 'music/2023 & Before/backwoods.mp3' },
      { title: 'baddiehub anthem', src: 'music/2023 & Before/baddiehub anthem.mp3' },
      { title: 'batman', src: 'music/2023 & Before/batman.mp3' },
      { title: 'deja vu', src: 'music/2023 & Before/deja vu.mp3' },
      { title: 'drug2me', src: 'music/2023 & Before/drug2me.mp3' },
      { title: 'everything (2022)', src: 'music/2023 & Before/everything (2022).mp3' },
      { title: 'freakbitch (remaster)', src: 'music/2023 & Before/freakbitch (remaster).mp3' },
      { title: 'g6', src: 'music/2023 & Before/g6.mp3' },
      { title: 'hardonthots', src: 'music/2023 & Before/hardonthots.mp3' },
      { title: 'imissyou', src: 'music/2023 & Before/imissyou.mp3' },
      { title: 'jail', src: 'music/2023 & Before/jail.mp3' },
      { title: 'jansport', src: 'music/2023 & Before/jansport.mp3' },
      { title: 'jucostar', src: 'music/2023 & Before/jucostar.mp3' },
      { title: 'kickrocks', src: 'music/2023 & Before/kickrocks.mp3' },
      { title: 'melodic life', src: 'music/2023 & Before/melodic life.mp3' },
      { title: 'moneyphaseuzi', src: 'music/2023 & Before/moneyphaseuzi.mp3' },
      { title: 'mouth piece', src: 'music/2023 & Before/mouth piece.mp3' },
      { title: 'narcissist', src: 'music/2023 & Before/narcissist.mp3' },
      { title: 'noway', src: 'music/2023 & Before/noway.mp3' },
      { title: 'omg', src: 'music/2023 & Before/omg.mp3' },
      { title: 'pulloutaflute', src: 'music/2023 & Before/pulloutaflute.mp3' },
      { title: 'rapperdudek', src: 'music/2023 & Before/rapperdudek.mp3' },
      { title: 'sevan v1', src: 'music/2023 & Before/sevan v1.mp3' },
      { title: 'streamon', src: 'music/2023 & Before/streamon.mp3' },
      { title: 'throwingfives', src: 'music/2023 & Before/throwingfives.mp3' },
      { title: 'truecolors', src: 'music/2023 & Before/truecolors.mp3' },
      { title: 'wtf', src: 'music/2023 & Before/wtf.mp3' }
    ]
  },
  {
    id: '2024',
    title: '2024',
    folder: '2024',
    cover: 'music/2024.webp',
    coverFallback: null,
    durationText: '',
    tracks: [
      { title: 'seasick (alt)', src: 'music/2024/seasick (alt).mp3' },
      { title: '1250', src: 'music/2024/1250.mp3' },
      { title: '12amintokyo', src: 'music/2024/12amintokyo.mp3' },
      { title: '1of1', src: 'music/2024/1of1.mp3' },
      { title: 'FEELAWAY', src: 'music/2024/FEELAWAY.mp3' },
      { title: 'SWATTEAM', src: 'music/2024/SWATTEAM.mp3' },
      { title: 'switchlanes V3', src: 'music/2024/_switchlanes_ V3.mp3' },
      { title: 'badhoesleavingbedstains', src: 'music/2024/badhoesleavingbedstains.mp3' },
      { title: 'ballin', src: 'music/2024/ballin.mp3' },
      { title: 'bangout', src: 'music/2024/bangout.mp3' },
      { title: 'beaverskin', src: 'music/2024/beaverskin.mp3' },
      { title: 'bebe', src: 'music/2024/bebe.mp3' },
      { title: 'blacktruck', src: 'music/2024/blacktruck.mp3' },
      { title: 'blackwing', src: 'music/2024/blackwing.mp3' },
      { title: 'butterflymydoors', src: 'music/2024/butterflymydoors.mp3' },
      { title: 'buttonmashin', src: 'music/2024/buttonmashin.mp3' },
      { title: 'camp', src: 'music/2024/camp.mp3' },
      { title: 'changelanes', src: 'music/2024/changelanes.mp3' },
      { title: 'clown', src: 'music/2024/clown.mp3' },
      { title: 'comethru', src: 'music/2024/comethru.mp3' },
      { title: 'deathnote', src: 'music/2024/deathnote.mp3' },
      { title: 'dieabout', src: 'music/2024/dieabout.mp3' },
      { title: 'drinkin n drivin', src: 'music/2024/drinkin n drivin.mp3' },
      { title: 'dust', src: 'music/2024/dust.mp3' },
      { title: 'extra', src: 'music/2024/extra.mp3' },
      { title: 'eyetoeye', src: 'music/2024/eyetoeye.mp3' },
      { title: 'fathersday', src: 'music/2024/fathersday.mp3' },
      { title: 'feeltoberich', src: 'music/2024/feeltoberich.mp3' },
      { title: 'fittedcaps', src: 'music/2024/fittedcaps.mp3' },
      { title: 'fiveforever', src: 'music/2024/fiveforever.mp3' },
      { title: 'holdyoustill', src: 'music/2024/holdyoustill.mp3' },
      { title: 'how2jerk', src: 'music/2024/how2jerk.mp3' },
      { title: 'huracan', src: 'music/2024/huracan.mp3' },
      { title: 'ionknow', src: 'music/2024/ionknow.mp3' },
      { title: 'je jure', src: 'music/2024/je jure.mp3' },
      { title: 'kobeyear', src: 'music/2024/kobeyear.mp3' },
      { title: 'madein15minutes', src: 'music/2024/madein15minutes.mp3' },
      { title: 'muscle', src: 'music/2024/muscle.mp3' },
      { title: 'needadoctor', src: 'music/2024/needadoctor.mp3' },
      { title: 'omg', src: 'music/2024/omg.mp3' },
      { title: 'opencarry', src: 'music/2024/opencarry.mp3' },
      { title: 'origami', src: 'music/2024/origami.mp3' },
      { title: 'outro', src: 'music/2024/outro.mp3' },
      { title: 'pinkeverything', src: 'music/2024/pinkeverything.mp3' },
      { title: 'place', src: 'music/2024/place.mp3' },
      { title: 'plastic hoes', src: 'music/2024/plastic hoes.mp3' },
      { title: 'problematic', src: 'music/2024/problematic.mp3' },
      { title: 'ptrrr', src: 'music/2024/ptrrr.mp3' },
      { title: 'purpose', src: 'music/2024/purpose.mp3' },
      { title: 'ramadan', src: 'music/2024/ramadan.mp3' },
      { title: 'realestate', src: 'music/2024/realestate.mp3' },
      { title: 'roscoes', src: 'music/2024/roscoes.mp3' },
      { title: 'runningback', src: 'music/2024/runningback.mp3' },
      { title: 'runningupbags', src: 'music/2024/runningupbags.mp3' },
      { title: 'seasick', src: 'music/2024/seasick.mp3' },
      { title: 'seeingred', src: 'music/2024/seeingred.mp3' },
      { title: 'seeinthings', src: 'music/2024/seeinthings.mp3' },
      { title: 'showit', src: 'music/2024/showit.mp3' },
      { title: 'somuch', src: 'music/2024/somuch.mp3' },
      { title: 'splurcetti', src: 'music/2024/splurcetti.mp3' },
      { title: 'stashingreen', src: 'music/2024/stashingreen.mp3' },
      { title: 'steplikerockstar', src: 'music/2024/steplikerockstar.mp3' },
      { title: 'suicide', src: 'music/2024/suicide.mp3' },
      { title: 'switchlanes', src: 'music/2024/switchlanes.mp3' },
      { title: 'thatsallright', src: 'music/2024/thatsallright.mp3' },
      { title: 'thetop', src: 'music/2024/thetop.mp3' },
      { title: 'topshelf', src: 'music/2024/topshelf.mp3' },
      { title: 'warningsign', src: 'music/2024/warningsign.mp3' },
      { title: 'wokeuprich', src: 'music/2024/wokeuprich.mp3' }
    ]
  },
  {
    id: '2026',
    title: '2026',
    folder: '2026',
    cover: 'music/2026.jpg',
    coverFallback: null,
    durationText: '',
    tracks: [
      { title: 'how you feel?', src: 'music/2026/how you feel.mp3' },
      { title: 'lost love', src: 'music/2026/lost love.mp3' },
      { title: 'actthatway', src: 'music/2026/actthatway.mp3' },
      { title: 'ballikeai', src: 'music/2026/ballikeai.mp3' },
      { title: 'bankrupt', src: 'music/2026/bankrupt.mp3' },
      { title: 'battleofthebands', src: 'music/2026/battleofthebands.mp3' },
      { title: 'belikeme', src: 'music/2026/belikeme.mp3' },
      { title: 'betterthings', src: 'music/2026/betterthings.mp3' },
      { title: 'chromebeater', src: 'music/2026/chromebeater.mp3' },
      { title: 'crackrightnow', src: 'music/2026/crackrightnow.mp3' },
      { title: 'feellikethis', src: 'music/2026/feellikethis.mp3' },
      { title: 'feltthat', src: 'music/2026/feltthat.mp3' },
      { title: 'firstdayback', src: 'music/2026/firstdayback.mp3' },
      { title: 'hesi', src: 'music/2026/hesi.mp3' },
      { title: 'issa issa', src: 'music/2026/issa issa.mp3' },
      { title: 'jimihendrix', src: 'music/2026/jimihendrix.mp3' },
      { title: 'machete', src: 'music/2026/machete.mp3' },
      { title: 'makeherfamous', src: 'music/2026/makeherfamous.mp3' },
      { title: 'nosebleeds', src: 'music/2026/nosebleeds.mp3' },
      { title: 'onarun', src: 'music/2026/onarun.mp3' },
      { title: 'outoftouch', src: 'music/2026/outoftouch.mp3' },
      { title: 'ouu shit', src: 'music/2026/ouushitfull.mp3' },
      { title: 'plaqueboybieber remaster (ai)', src: 'music/2026/plaqueboybieber remaster (ai).mp3' },
      { title: 'president', src: 'music/2026/president.mp3' },
      { title: 'shakemydreads', src: 'music/2026/shakemydreads.mp3' },
      { title: 'switchedup', src: 'music/2026/switchedup.mp3' },
      { title: 'thongsong', src: 'music/2026/thongsong.mp3' },
      { title: 'trendingtopic', src: 'music/2026/trendingtopic.mp3' },
      { title: 'twotime', src: 'music/2026/twotime.m4a' },
      { title: 'wejustwannaparty', src: 'music/2026/wejustwannaparty.mp3' }
    ]
  },
  {
    id: 'break',
    title: 'BREAK',
    folder: 'break',
    cover: 'music/break.webp',
    coverFallback: 'music/break/Folder.jpg',
    durationText: '',
    tracks: [
      { title: 'ACTING OUT', src: 'music/break/ACTING OUT.mp3' },
      { title: 'FATBOYZ', src: 'music/break/FATBOYZ.mp3' },
      { title: 'FIVESTARFILM', src: 'music/break/FIVESTARFILM.mp3' },
      { title: 'FIVESTARHOES', src: 'music/break/FIVESTARHOES.mp3' },
      { title: 'KARRUECHE-PEEWEE', src: 'music/break/KARRUECHE-PEEWEE.mp3' },
      { title: 'MANOFMYCITY', src: 'music/break/MANOFMYCITY.mp3' },
      { title: 'MILLIONDOLLARBABY', src: 'music/break/MILLIONDOLLARBABY.mp3' },
      { title: 'PINK CHROME', src: 'music/break/PINK CHROME.mp3' },
      { title: 'SUPER RATCHET', src: 'music/break/SUPER RATCHET.mp3' },
      { title: 'TOOMUCHBANDS', src: 'music/break/TOOMUCHBANDS.mp3' },
      { title: 'YEAYEA (windoshop)', src: 'music/break/YEAYEA (windoshop).mp3' },
      { title: 'YOUDECIDE', src: 'music/break/YOUDECIDE.mp3' }
    ]
  },
  {
    id: 'fiveforever-v1',
    title: 'FIVEFOREVER V1',
    folder: 'fiveforever v1',
    cover: 'music/fiveforever v1/! cover.jpg',
    coverFallback: 'music/fiveforever v1/Folder.jpg',
    durationText: '',
    tracks: [
      { title: 'birdsdontflyaway', src: 'music/fiveforever v1/01 _birdsdontflyaway_ V1.mp3' },
      { title: 'cmb', src: 'music/fiveforever v1/02 _cmb_ V1.mp3' },
      { title: 'plainjane', src: 'music/fiveforever v1/03 _plainjane_ V1.mp3' },
      { title: 'helmut lang', src: 'music/fiveforever v1/04 _helmut lang_ V1.mp3' },
      { title: 'yellowlambtruck', src: 'music/fiveforever v1/05 _yellowlambtruck_ V1.mp3' },
      { title: 'clear', src: 'music/fiveforever v1/06 _clear_ V1.mp3' },
      { title: 'plussizebags', src: 'music/fiveforever v1/07 _plussizebags_ V1.mp3' },
      { title: 'rickpants', src: 'music/fiveforever v1/08 _rickpants_ V1.mp3' },
      { title: 'dumb&dumber', src: 'music/fiveforever v1/09 _dumb&dumber_ V1.mp3' },
      { title: 'stopstealinswag', src: 'music/fiveforever v1/10 _stopstealinswag_ V1.mp3' },
      { title: 'escalade', src: 'music/fiveforever v1/11 _escalade_ V1.mp3' },
      { title: 'lamebae', src: 'music/fiveforever v1/12 _lamebae_ V1.mp3' },
      { title: 'gold', src: 'music/fiveforever v1/13 _gold_ V1.mp3' },
      { title: 'you should know', src: 'music/fiveforever v1/14 _you should know_ V1.mp3' }
    ]
  },
  {
    id: 'newcrib',
    title: 'NEWCRIB',
    folder: 'newcrib',
    cover: 'music/newcrib.jpg',
    coverFallback: 'music/newcrib/Folder.jpg',
    durationText: '',
    tracks: [
      { title: 'hatinahhhh', src: 'music/newcrib/13 _hatinahhhh_ V1.mp3' },
      { title: 'pacifier', src: 'music/newcrib/26 _pacifier_ V1.mp3' },
      { title: 'malibutides', src: 'music/newcrib/27 _malibutides_ V1.mp3' },
      { title: 'MORROCCO', src: 'music/newcrib/29 _MORROCCO_ V1.mp3' },
      { title: 'ELVISPRESLEY', src: 'music/newcrib/ELVISPRESLEY.mp3' },
      { title: 'JUSTAPHASE', src: 'music/newcrib/JUSTAPHASE.mp3' },
      { title: 'toonice', src: 'music/newcrib/_toonice_ V3.mp3' },
      { title: 'mojave ghost', src: 'music/newcrib/mojave ghost.mp3' },
      { title: 'moonrock', src: 'music/newcrib/moonrock.mp3' },
      { title: 'motto', src: 'music/newcrib/motto.mp3' },
      { title: 'onlythefamily (ft. fbd)', src: 'music/newcrib/onlythefamily (ft. fbd).mp3' },
      { title: 'swagitout', src: 'music/newcrib/swagitout.mp3' },
      { title: 'twentythree', src: 'music/newcrib/twentythree.mp3' }
    ]
  },
  {
    id: 'pbm2025',
    title: 'PBM2025',
    folder: 'pbm2025',
    cover: 'music/pbm2025.webp',
    coverFallback: null,
    durationText: '',
    tracks: [
      { title: 'rockstar', src: 'music/pbm2025/01 _rockstar_ V1.mp3' },
      { title: 'scream', src: 'music/pbm2025/02 _scream_ V1.mp3' },
      { title: 'gokart', src: 'music/pbm2025/03 _gokart_ V1.mp3' },
      { title: 'superwrong', src: 'music/pbm2025/04 _superwrong_ V1.mp3' },
      { title: 'doja', src: 'music/pbm2025/05 _doja_ V1.mp3' },
      { title: '4doors', src: 'music/pbm2025/06 _4doors_ V1.mp3' },
      { title: 'dave', src: 'music/pbm2025/07 _dave_ V1.mp3' },
      { title: 'change', src: 'music/pbm2025/08 _change_ V2.mp3' },
      { title: 'p&y', src: 'music/pbm2025/09 _p&y_ V1.mp3' },
      { title: 'fieldtrips', src: 'music/pbm2025/10 _fieldtrips_ V1.mp3' },
      { title: 'pinkbottles', src: 'music/pbm2025/11 _pinkbottles_ V1.mp3' },
      { title: 'fiveforever', src: 'music/pbm2025/12 _fiveforever_ V3.mp3' },
      { title: 'hellyeah', src: 'music/pbm2025/13 _hellyeah_ V2.mp3' },
      { title: 'smh', src: 'music/pbm2025/14 _smh_ V1.mp3' },
      { title: '2016', src: 'music/pbm2025/15 _2016_ V2.mp3' },
      { title: 'layflat', src: 'music/pbm2025/16 _layflat_ V1.mp3' },
      { title: 'poltergeist', src: 'music/pbm2025/17 _poltergeist_ V1.mp3' },
      { title: 'sevant', src: 'music/pbm2025/18 _sevant_ V2.mp3' },
      { title: 'bentleytruckswerve', src: 'music/pbm2025/19 _bentleytruckswerve_ V1.mp3' },
      { title: 'swag', src: 'music/pbm2025/20 _swag_ V1.mp3' },
      { title: '22', src: 'music/pbm2025/21 _22_ V1.mp3' },
      { title: 'tankdavis', src: 'music/pbm2025/22 _tankdavis_ V1.mp3' },
      { title: 'yacht', src: 'music/pbm2025/23 _yacht_ V1.mp3' },
      { title: 'eastcoastnigga', src: 'music/pbm2025/24 _eastcoastnigga_ V1.mp3' },
      { title: 'hawaii', src: 'music/pbm2025/25 _hawaii_ V1.mp3' },
      { title: 'wyd', src: 'music/pbm2025/26 _wyd_ V1.mp3' },
      { title: 'casperrrrr', src: 'music/pbm2025/27 _casperrrrr_ V2.mp3' },
      { title: 'yacht2', src: 'music/pbm2025/29 _yacht2_ V1.mp3' },
      { title: 'atlanta', src: 'music/pbm2025/30 _atlanta_ V1.mp3' },
      { title: 'starwagoncoupe', src: 'music/pbm2025/33 _starwagoncoupe_ V8.mp3' },
      { title: 'swag2', src: 'music/pbm2025/35 _swag2_ V1.mp3' },
      { title: 'paidforrrr', src: 'music/pbm2025/37 _paidforrrr_ V1.mp3' },
      { title: 'SOSSS', src: 'music/pbm2025/38 _SOSSS_ V1.mp3' },
      { title: 'stupidhoe', src: 'music/pbm2025/stupidhoe.mp3' },
      { title: 'swag 3', src: 'music/pbm2025/swag 3.mp3' }
    ]
  },
  {
    id: 'prince',
    title: 'PRINCE',
    folder: 'prince',
    cover: 'music/prince.png',
    coverFallback: null,
    durationText: '',
    tracks: [
      { title: 'rip lil peep', src: 'music/prince/riplilpeep.mp3' },
      { title: 'battleofthebands', src: 'music/prince/battleofthebands.mp3' },
      { title: 'hesi', src: 'music/prince/hesi.mp3' },
      { title: 'howtf', src: 'music/prince/howtf.mp3' },
      { title: 'jimihendrix', src: 'music/prince/jimihendrix.mp3' },
      { title: 'vendetta (credit @5iveplug)', src: 'music/prince/vendetta.mp3' }
    ]
  },
  {
    id: 'untitled-project',
    title: 'UNTITLED PROJECT',
    folder: 'untitled project',
    cover: 'music/untitled.png',
    coverFallback: 'music/untitled project/Folder.jpg',
    durationText: '',
    tracks: [
      { title: '3or2', src: 'music/untitled project/3or2.mp3' },
      { title: 'beenhadswagnigguhhhh', src: 'music/untitled project/beenhadswagnigguhhhh.mp3' },
      { title: 'chromeheartschucks', src: 'music/untitled project/chromeheartschucks.mp3' },
      { title: 'kbkbkb', src: 'music/untitled project/kbkbkb.mp3' }
    ]
  },
  {
    id: 'xtra',
    title: 'XTRA',
    folder: 'xtra',
    cover: 'music/xtra.webp',
    coverFallback: 'music/xtra/Folder.jpg',
    durationText: '',
    tracks: [
      { title: 'badbusiness', src: 'music/xtra/badbusiness.mp3' },
      { title: 'deadniggasmakeitfeelshort', src: 'music/xtra/deadniggasmakeitfeelshort.mp3' },
      { title: 'moty2.5', src: 'music/xtra/moty2.5.mp3' },
      { title: 'pbm onlythefamily 11.30.25', src: 'music/xtra/pbm onlythefamily 11.30.25.wav' },
      { title: 'plaqueboymax', src: 'music/xtra/plaqueboymax.mp3' },
      { title: 'yuhhh', src: 'music/xtra/yuhhh.mp3' }
    ]
  }
];

function getProject(id) {
  return MUSIC_LIBRARY.find(p => p.id === id) || null;
}
